services:
  - type: web
    name: careplus-simple
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: development
      - key: DATABASE_URL
        value: postgresql://careplus_user:2b3rlfLfFCbQQ5ZZfdNdJGM3QHjLAGQL@dpg-d27mqqruibrs738koae0-a.ohio-postgres.render.com/careplus_db_x5qn
      - key: SESSION_SECRET
        value: careplus_secure_secret_2025